[package]
name = "craftec-distribution-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
craftec-prover-guest-types = { path = "../prover-guest-types" }
sp1-zkvm = "5.2"
sha2 = "0.10"
